#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Copy mesh
cp -r ../polyMesh constant/

# decompose the case (number of decompositions is equal to --ntasks)
runApplication decomposePar

# run parallel
echo "Start $(getApplication) in parallel. Log is written in case/log.$(getApplication)!"
runParallel $(getApplication)
#mpirun -n 6  $(getApplication) -parallel > log.$(getApplication) 2>&1

runApplication reconstructPar -latestTime

simpleFoam -postProcess -func foil_sample -latestTime
simpleFoam -postProcess -func forces -latestTime
