#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Initialize phi with potential flow
runApplication $(getApplication) -writep
runApplication postProcess -func streamFunction

