#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

module purge
module load openfoam-2112-gcc-11.2.0-lhrpyq4


# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# if $(getaApplication) does not work
appName=$1


# ***********************************
# *** run it in NON-parallel mode ***
# ***********************************

echo "Start $appName in parallel. Log is written in case/log.$appName!"
runApplication $appName 


# **************************************************
# *** cusomize it for parallel run on HPC system ***
# **************************************************

# decompose the case (number of decompositions is equal to --ntasks)
#runApplication decomposePar

# run parallel
#echo "Start $appName in parallel. Log is written in case/log.$appName!"
#runParallel $appName &
#mpirun -n 6  $appName -parallel > log.$appName 2>&1

runApplication reconstructPar -latestTime

$(getApplication) -postProcess -func foil_sample -latestTime
$(getApplication) -postProcess -func forces -latestTime
$(getApplication) -postProcess -func yplus -latestTime
